# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.SmallIntegerField()),
                ('sample_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SampleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=250)),
                ('number_of_samples', models.SmallIntegerField()),
                ('samples_set_description', models.CharField(max_length=2000)),
                ('registration_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.SampleSet'),
        ),
    ]
