# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20170327_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleset',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
