# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import sample.models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20170330_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleset',
            name='set_name',
            field=models.CharField(default=sample.models.get_set_name, editable=False, max_length=250),
        ),
    ]
