# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_auto_20170331_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleset',
            name='final_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
